# Generated by Django 3.0.6 on 2020-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cod_relatorio', models.IntegerField()),
                ('cod_empresa', models.IntegerField()),
                ('cod_atracao', models.IntegerField()),
                ('local', models.CharField(max_length=60)),
                ('data', models.DateTimeField()),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
    ]
